FROM openjdk:8-jre
MAINTAINER Klaus Hebsgaaard <klaus.hebsgaard@jp.dk>

# much credit goes to :
# https://hub.docker.com/r/williamyeh/scala/~/dockerfile/
ENV SCALA_VERSION 2.12.0 
ENV SCALA_TARBALL http://www.scala-lang.org/files/archive/scala-$SCALA_VERSION.deb 

RUN \
echo "==> Install curl helper tool..." && \
apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes curl && \
\
\
\
echo "===> install from Typesafe repo (contains old versions but they have all dependencies we need later on)" && \
curl -sSL http://apt.typesafe.com/repo-deb-build-0002.deb -o repo-deb.deb && \
dpkg -i repo-deb.deb && \
apt-get update && \
\
\
\
echo "===> install Scala" && \
DEBIAN_FRONTEND=noninteractive \
apt-get install -y --force-yes libjansi-java && \
curl -sSL $SCALA_TARBALL -o scala.deb && \
dpkg -i scala.deb && \
\
\
\
echo "===> clean up..." && \
rm -f *.deb && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

COPY ./snowplow/2-collectors/scala-stream-collector/target/scala-2.10/snowplow-stream-collector-0.9.0 /app/snowplow-stream-collector-0.9.0.jar
COPY ./scalacollector/configuration/config /app/configuration/config
CMD /app/snowplow-stream-collector-0.9.0.jar --config /app/configuration/config
